import { makeClient } from '../ipc/ipc';

export const clientStub = ipcRendererInjector => makeClient(ipcRendererInjector, 'Node', [
  'start',
  'stop',
  'reset',
  'generateToAddress',
  'getAPIKey',
  'getNoDns',
  'getSpvMode',
  'getInfo',
  'getNameInfo',
  'getTXByAddresses',
  'getNameByHash',
  'getBlockByHeight',
  'getTx',
  'broadcastRawTx',
  'sendRawAirdrop',
  'getFees',
  'getAverageBlockTime',
  'getMTP',
  'getCoin',
  'verifyMessageWithName',
  'setNodeDir',
  'setAPIKey',
  'setNoDns',
  'setSpvMode',
  'getDir',
  'getAPIKey',
  'getHNSPrice',
  'testCustomRPCClient',
  'getDNSSECProof',
  'sendRawClaim',
]);
