# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: ['18']

        # OS-specific commands/variables
        include:
          - os: ubuntu-latest
            cmd_build: npm run build
          - os: windows-latest
            cmd_build: node .\scripts\package.js

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install libudev-dev libusb-1.0-0-dev -y

      - name: Install npm packages
        run: npm i

      - name: Build
        run: ${{ matrix.cmd_build }}

      - name: Test
        run: npm test
